version: '3'

services:
    nginx:
        build: ./nginx
        container_name: nginx
        networks:
            - thenet
        ports:
            - ${NGINX_PORT}:80
    app:
        build: ./app
        container_name: app
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - thenet
        # unccomment for direct http://localhost:3000
        # ports:
        #     - 3000:3000

networks:
    thenet: